In [51]:
import numpy as np
a = np.array([1,2,3,4,5,6,9])
b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(type(a))
print(a)
print(type(b))
print(b[0,1])

<class 'numpy.ndarray'>
[1 2 3 4 5 6 9]
<class 'numpy.ndarray'>
2


hacer una lista de impa

In [52]:
a = np.linspace(1,9,5)
print(a)
b = np.arange(1,10,2)
print(b)
c = np.concatenate((a,b))
print(c)


[1. 3. 5. 7. 9.]
[1 3 5 7 9]
[1. 3. 5. 7. 9. 1. 3. 5. 7. 9.]


In [53]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
z = np.concatenate((x,y),0)
t = np.concatenate((x,y),1)
print(x,y)
print(z)
print(t)

[[1 2]
 [3 4]] [[5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [54]:
array_ejemplo = [
    [[0,1,2,3],[4,5,6,7]],
    [[8,9,10,11],[12,13,14,15]],
    [[16,17,18,19],[20,21,22,23]]
]

array_ejemplo = np.array(array_ejemplo)

print(array_ejemplo)
print(array_ejemplo.ndim,array_ejemplo.shape,array_ejemplo.size)

print(array_ejemplo.reshape(12,2))

nueva = array_ejemplo.reshape((3,-1))
print(nueva)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]
3 (3, 2, 4) 24
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]


In [57]:
a = np.array([1,2])
b = np.ones(2)

c = a + b
d = a - b

print(a.sum())
print(c)
print(d)


3
[2. 3.]
[0. 1.]


In [61]:
data = np.array([[1,2],[3,4],[5,6]])
print(data[0,1])
print(data[1:3])
print(data[1:3,1])

2
[[3 4]
 [5 6]]
[4 6]


In [70]:
def pisar_elemento(M,e):
    M_shape = M.shape
    lista_M = M.reshape(M.size)
    copia_lista = []
    for i in lista_M:
        if i == e:
            copia_lista.append(-1)
        else:
            copia_lista.append(i)
    salida_lista = np.array(copia_lista)
    salida = salida_lista.reshape(M_shape)
    return salida

ejemplo_M = np.array([[[0,1,2,3],[4,5,6,7],[2,2,2,2]],[[2,2,1,2],[3,3,2,4,],[5,6,7,2]]])
e = 2

print(ejemplo_M)
print(pisar_elemento(ejemplo_M, e))

[[[0 1 2 3]
  [4 5 6 7]
  [2 2 2 2]]

 [[2 2 1 2]
  [3 3 2 4]
  [5 6 7 2]]]
[[[ 0  1 -1  3]
  [ 4  5  6  7]
  [-1 -1 -1 -1]]

 [[-1 -1  1 -1]
  [ 3  3 -1  4]
  [ 5  6  7 -1]]]


In [23]:
import pandas as pd
import os

archivo = 'arbolado-en-espacios-verdes.csv'
fname = os.path.join(archivo)
df = pd.read_csv(fname)

df.head()
df.columns
df.index
df[['altura_tot', 'diametro', 'inclinacio']].describe()
df['nombre_com'] == 'Ombú'
df['nombre_com'].unique()
cant_ejemplares = df['nombre_com'].value_counts()
cant_ejemplares.head(10) # tabla con los 10 nombres más frecuentes
df_jacarandas = df[df['nombre_com'] == 'Jacarandá']
cols = ['altura_tot', 'diametro', 'inclinacio']
df_jacarandas = df_jacarandas[cols]
df_jacarandas.tail()
df_jacarandas = df[df['nombre_com'] == 'Jacarandá'][cols].copy()
df_jacarandas
diametros = df_jacarandas['diametro']
type(diametros)

pandas.core.series.Series

In [82]:
import pandas as pd
import os

archivo = 'arbolado-en-espacios-verdes.csv'
fname = os.path.join(archivo)
data_arboles_parques = pd.read_csv(fname)
data_jacaranda = data_arboles_parques[data_arboles_parques["nombre_com"] == "Jacarandá"]
data_palos_borrachos = data_arboles_parques[data_arboles_parques["nombre_com"] == "Palo borracho"]

altura_jacaranda = data_jacaranda["altura_tot"]
diametro_jacaranda = data_jacaranda["diametro"]

print("datos Jacaranda")
print(f"cantidad de arboles = {data_jacaranda.count()[0]}")
print(f"altura maxima = {altura_jacaranda.max()} mts ")
print(f"altura minima = {altura_jacaranda.min()} mts")
print(f"altura promedio = {altura_jacaranda.mean()} mts")
print(f"diametro maxima = {diametro_jacaranda.max()} mts ")
print(f"diametro minima = {diametro_jacaranda.min()} mts")
print(f"diametro promedio = {diametro_jacaranda.mean()} mts")

altura_palo_borracho = data_palos_borrachos["altura_tot"]
diametro_palo_borracho = data_palos_borrachos["diametro"]

print("datos palos borrachos")
print(f"cantidad de arboles = {data_palos_borrachos.count()[0]}")
print(f"altura maxima = {altura_palo_borracho.max()} mts ")
print(f"altura minima = {altura_palo_borracho.min()} mts")
print(f"altura promedio = {altura_palo_borracho.mean()} mts")
print(f"diametro maxima = {diametro_palo_borracho.max()} mts ")
print(f"diametro minima = {diametro_palo_borracho.min()} mts")
print(f"diametro promedio = {diametro_palo_borracho.mean()} mts")

data_arboles_parques

datos Jacaranda
cantidad de arboles = 3255
altura maxima = 49 mts 
altura minima = 1 mts
altura promedio = 10.369585253456222 mts
diametro maxima = 159 mts 
diametro minima = 1 mts
diametro promedio = 28.804301075268818 mts
datos palos borrachos
cantidad de arboles = 119
altura maxima = 33 mts 
altura minima = 1 mts
altura promedio = 9.882352941176471 mts
diametro maxima = 130 mts 
diametro minima = 1 mts
diametro promedio = 43.436974789915965 mts


long        lat  id_arbol  altura_tot  diametro  inclinacio   
0     -58.477564 -34.645015         1           6        35           0  \
1     -58.477559 -34.645047         2           6        35           0   
2     -58.477551 -34.645091         3           6        35           0   
3     -58.478129 -34.644567         4          17        50           0   
4     -58.478121 -34.644598         5          17        50           0   
...          ...        ...       ...         ...       ...         ...   
51497 -58.505752 -34.562998     51725          15        30           0   
51498 -58.507111 -34.565843     51726          13        31           0   
51499 -58.475721 -34.565192     51727          11        28           0   
51500 -58.507026 -34.565670     51728           5        32           0   
51501 -58.506874 -34.565334     51729          10        35           0   

       id_especie                                       nombre_com   
0              53              Washingtonia (Palmera washingtonia)  \
1              53              Washingtonia (Palmera washingtonia)   
2              53              Washingtonia (Palmera washingtonia)   
3              65                                             Ombú   
4              65                                             Ombú   
...           ...                                              ...   
51497          45                                        Casuarina   
51498          45                                        Casuarina   
51499          17  Árbol del cielo (Ailanto o Árbol de los dioses)   
51500         342                                           Ciprés   
51501         342                                           Ciprés   

                     nombre_cie                     tipo_folla   
0         Washingtonia filifera                        Palmera  \
1         Washingtonia filifera                        Palmera   
2         Washingtonia filifera                        Palmera   
3             Phytolacca dioica  Árbol Latifoliado Caducifolio   
4             Phytolacca dioica  Árbol Latifoliado Caducifolio   
...                         ...                            ...   
51497  Casuarina cunninghamiana      Árbol Latifoliado Perenne   
51498  Casuarina cunninghamiana      Árbol Latifoliado Perenne   
51499       Ailanthus altissima  Árbol Latifoliado Caducifolio   
51500             Cupressus sp.         Árbol Conífero Perenne   
51501             Cupressus sp.         Árbol Conífero Perenne   

                       espacio_ve   
0      AVELLANEDA, NICOLÁS, Pres.  \
1      AVELLANEDA, NICOLÁS, Pres.   
2      AVELLANEDA, NICOLÁS, Pres.   
3      AVELLANEDA, NICOLÁS, Pres.   
4      AVELLANEDA, NICOLÁS, Pres.   
...                           ...   
51497                 GENERAL PAZ   
51498                 GENERAL PAZ   
51499  CAMPELO, LICENCIADO CARLOS   
51500                 GENERAL PAZ   
51501                 GENERAL PAZ   

                                               ubicacion     nombre_fam   
0      DIRECTORIO, AV. - LACARRA, AV. - MONTE -  AUTO...      Arecaceas  \
1      DIRECTORIO, AV. - LACARRA, AV. - MONTE -  AUTO...      Arecaceas   
2      DIRECTORIO, AV. - LACARRA, AV. - MONTE -  AUTO...      Arecaceas   
3      DIRECTORIO, AV. - LACARRA, AV. - MONTE -  AUTO...   Fitolacáceas   
4      DIRECTORIO, AV. - LACARRA, AV. - MONTE -  AUTO...   Fitolacáceas   
...                                                  ...            ...   
51497  LARRALDE, CRISOLOGO, AV. - PAZ, GRAL., AV.- AI...  Casuarinaceas   
51498  LARRALDE, CRISOLOGO, AV. - PAZ, GRAL., AV.- AI...  Casuarinaceas   
51499  ESTACIÓN COGHLAN - Propiedad particular e/UGAR...  Simarrubáceas   
51500  LARRALDE, CRISOLOGO, AV. - PAZ, GRAL., AV.- AI...    Cupresáceas   
51501  LARRALDE, CRISOLOGO, AV. - PAZ, GRAL., AV.- AI...    Cupresáceas   

         nombre_gen            origen       coord_x        coord_y  
0      Washingtonia           Exótico  98692.305719   98253.30